image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build

before_script:
  - dotnet --version

# Build
build_model:
  stage: build
  script:
    - dotnet build RctByTN.Model

build_view:
  stage: build
  tags: [windows]
  script:
    - dotnet build RctByTN.sln
